// 出どころ: lilToon 2.3.4（MIT、Copyright (c) 2020-present lilxyzw）のプロパティの並び。許諾と出どころの全文は ../THIRD-PARTY-NOTICES.md。
// 値の並び（look_gpu.rs の `params` と同じ）
const P_MODE: i32 = 0;            // x 描画モード（0 不透明・1 カットアウト・2 半透明）、y Cutoff、z Cull、w 非表示
const P_COLOR: i32 = 1;           // _Color（リニア）
const P_MAIN_ST: i32 = 2;
const P_HSVG: i32 = 3;
const P_LIGHT: i32 = 4;           // x 下限、y 上限、z モノクロ化、w Unlit 化
const P_LIGHT2: i32 = 5;          // x 影色への環境光、y AA、z 裏面を影に、w 裏面の法線を反転
const P_LIGHT_DIR: i32 = 6;       // _LightDirectionOverride
const P_BACKFACE: i32 = 7;        // _BackfaceColor（リニア）
const P_ALPHA_MASK: i32 = 8;      // x モード、y スケール、z オフセット
const P_SHADOW: i32 = 9;          // x 入、y 強度、z マスクの種類、w 影範囲設定を無視
const P_SHADOW_LOD: i32 = 10;     // x 強度マスク、y AO、z ぼかしマスク
const P_SHADOW_FLAT: i32 = 11;    // x 平面の範囲、y 平面のぼかし、z 境界の幅、w コントラスト
const P_SHADOW1_COLOR: i32 = 12;
const P_SHADOW1: i32 = 13;        // x 範囲、y ぼかし、z ノーマルマップ強度、w 影を受け取る
const P_SHADOW2_COLOR: i32 = 14;
const P_SHADOW2: i32 = 15;
const P_SHADOW3_COLOR: i32 = 16;
const P_SHADOW3: i32 = 17;
const P_SHADOW_BORDER_COLOR: i32 = 18;
const P_AO_SHIFT: i32 = 19;
const P_AO_SHIFT2: i32 = 20;
const P_EMISSION: i32 = 21;       // x 入、y 強度、z 合成モード、w メインカラーの強度
const P_EMISSION_COLOR: i32 = 22;
const P_EMISSION_ST: i32 = 23;
const P_EMISSION_MASK_ST: i32 = 24;
const P_EMISSION_X: i32 = 25;     // x 蛍光、y UV、z テクスチャの角度、w マスクの角度
const P_EMISSION2: i32 = 26;
const P_EMISSION2_COLOR: i32 = 27;
const P_EMISSION2_ST: i32 = 28;
const P_EMISSION2_MASK_ST: i32 = 29;
const P_EMISSION2_X: i32 = 30;
const P_BUMP: i32 = 31;           // x 入、y 強度
const P_BUMP_ST: i32 = 32;
const P_MATCAP: i32 = 33;         // x 入、y 強度、z 合成モード、w メインカラーの強度
const P_MATCAP_COLOR: i32 = 34;
const P_MATCAP_ST: i32 = 35;
const P_MATCAP_MASK_ST: i32 = 36;
const P_MATCAP_P: i32 = 37;       // x ライトの明るさ、y 影部分で無効化、z 裏面で無効化、w ぼかし
const P_MATCAP_Q: i32 = 38;       // x ノーマルマップ強度、y Z 軸回転キャンセル、z パース補正、w 透明度を適用
const P_MATCAP2: i32 = 39;
const P_MATCAP2_COLOR: i32 = 40;
const P_MATCAP2_ST: i32 = 41;
const P_MATCAP2_MASK_ST: i32 = 42;
const P_MATCAP2_P: i32 = 43;
const P_MATCAP2_Q: i32 = 44;
const P_RIM: i32 = 45;            // x 入、y 合成モード、z メインカラーの強度、w ノーマルマップ強度
const P_RIM_COLOR: i32 = 46;
const P_RIM_ST: i32 = 47;
const P_RIM_P: i32 = 48;          // x 範囲、y ぼかし、z 細さ、w ライトの明るさ
const P_RIM_Q: i32 = 49;          // x 影部分で無効化、y 裏面で無効化、z 透明度を適用、w ライト方向の影響度
const P_RIM_R: i32 = 50;          // x 直接光の幅、y 間接光の幅、z 間接光の範囲、w 間接光のぼかし
const P_RIM_INDIR_COLOR: i32 = 51;
const P_OUTLINE: i32 = 52;        // x 入、y 太さ、z 距離補正、w ライトの明るさ
const P_OUTLINE_COLOR: i32 = 53;
const P_OUTLINE_ST: i32 = 54;
const P_OUTLINE_HSVG: i32 = 55;
const P_OUTLINE_LIT_COLOR: i32 = 56;
const P_OUTLINE_P: i32 = 57;      // x スケール、y オフセット、z メインカラーから、w 影を受け取る
const P_OUTLINE_Q: i32 = 58;      // x Z バイアス、y 太さ 0 を消す、z テクスチャの角度
const P_FLAGS: i32 = 59;          // x 法線マップを読める（接線がある）
const P_UV: i32 = 60;             // x メインの UV の角度、y 裏面の UV をずらす
// メインカラー 2nd（61〜69）・3rd（70〜78）: 同じ並び（L_*）
const P_LAYER2: i32 = 61;
const P_LAYER3: i32 = 70;
const L_P: i32 = 0;               // x 入、y ライトの明るさ、z 合成モード、w 透過モード
const L_COLOR: i32 = 1;           // 色（リニア）
const L_ST: i32 = 2;
const L_Q: i32 = 3;               // x 角度、y UV（0 UV0・4 マットキャップ）、z Cull、w MSDF
const L_DECAL: i32 = 4;           // x デカール、y 左のみ、z 右のみ、w 複製
const L_DECAL2: i32 = 5;          // x ミラーの反転、y 複製の反転
const L_ANIM: i32 = 6;            // _<名>TexDecalAnimation
const L_SUB: i32 = 7;             // _<名>TexDecalSubParam
const L_FADE: i32 = 8;            // _<名>DistanceFade
const P_BUMP2: i32 = 79;          // x 入、y 強度
const P_BUMP2_ST: i32 = 80;
const P_RIM_SHADE: i32 = 81;      // x 入、y ノーマルマップ強度、z 範囲、w ぼかし
const P_RIM_SHADE_COLOR: i32 = 82;
const P_RIM_SHADE2: i32 = 83;     // x 細さ
const P_BACKLIGHT: i32 = 84;      // x 入、y メインカラーの強度、z 影を受け取る、w 裏面で無効化
const P_BACKLIGHT_COLOR: i32 = 85;
const P_BACKLIGHT_P: i32 = 86;    // x ノーマルマップ強度、y 範囲、z ぼかし、w 指向性
const P_BACKLIGHT_Q: i32 = 87;    // x 視線方向の影響度
const P_BACKLIGHT_ST: i32 = 88;
const P_REFL: i32 = 89;           // x 入、y 滑らかさ、z 金属度（リニア）、w 反射率（リニア）
const P_REFL_COLOR: i32 = 90;
const P_REFL_P: i32 = 91;         // x 光沢を出す、y トゥーン、z 光沢のノーマルマップ強度、w 光沢の範囲
const P_REFL_Q: i32 = 92;         // x 光沢のぼかし、y 環境光の反射、z 反射のノーマルマップ強度、w 透明度を適用
const P_REFL_R: i32 = 93;         // x 合成モード、y GSAA
const P_SMOOTH_ST: i32 = 94;
const P_METAL_ST: i32 = 95;
const P_REFL_COLOR_ST: i32 = 96;
const P_GLITTER: i32 = 97;        // x 入、y UV、z メインカラーの強度、w ライトの明るさ
const P_GLITTER_COLOR: i32 = 98;
const P_GLITTER_ST: i32 = 99;
const P_GLITTER_P1: i32 = 100;    // _GlitterParams1
const P_GLITTER_P2: i32 = 101;    // _GlitterParams2
const P_GLITTER_Q: i32 = 102;     // x 影部分で無効化、y 裏面で無効化、z 透明度を適用、w ノーマルマップ強度
const P_GLITTER_R: i32 = 103;     // x コントラスト（後処理）、y 感度、z 大きさのランダム化
const P_ANISO: i32 = 104;         // x 入、y スケール、z 反射へ、w マットキャップへ
const P_ANISO_Q: i32 = 105;       // x マットキャップ 2nd へ
const P_ANISO1: i32 = 106;        // タンジェント方向の幅・バイタンジェント方向の幅・オフセット・ノイズの強度（1st）
const P_ANISO2: i32 = 107;        // 同じ（2nd）
const P_ANISO_S: i32 = 108;       // x 1st の強度、y 2nd の強度
const P_ANISO_ST: i32 = 109;
const P_ANISO_MASK_ST: i32 = 110;
const P_ANISO_NOISE_ST: i32 = 111;
const P_DFADE_COLOR: i32 = 112;
const P_DFADE: i32 = 113;         // _DistanceFade
const P_DFADE_RIM_COLOR: i32 = 114;
const P_DFADE_P: i32 = 115;       // x モード、y リムの細さ
const P_MC_BUMP: i32 = 116;       // x 1st のカスタムノーマル、y その強度、z 2nd のカスタムノーマル、w その強度
const P_MC_BUMP_ST: i32 = 117;
const P_MC2_BUMP_ST: i32 = 118;
const P_ALPHA_MASK_ST: i32 = 119;
const P_DFADE_ORIGIN: i32 = 120;  // モデルの原点（座標のモードの距離）

// スロット（liltoon.rs の SLOTS と同じ並び）
const SLOT_MAIN: i32 = 0;
const SLOT_ADJUST_MASK: i32 = 1;
const SLOT_ALPHA_MASK: i32 = 2;
const SLOT_BUMP: i32 = 3;
const SLOT_SHADOW_STRENGTH: i32 = 4;
const SLOT_SHADOW_BORDER: i32 = 5;
const SLOT_SHADOW_BLUR: i32 = 6;
const SLOT_SHADOW1_TEX: i32 = 7;
const SLOT_SHADOW2_TEX: i32 = 8;
const SLOT_SHADOW3_TEX: i32 = 9;
const SLOT_EMISSION: i32 = 10;
const SLOT_EMISSION_MASK: i32 = 11;
const SLOT_EMISSION2: i32 = 12;
const SLOT_EMISSION2_MASK: i32 = 13;
const SLOT_MATCAP: i32 = 14;
const SLOT_MATCAP_MASK: i32 = 15;
const SLOT_MATCAP2: i32 = 16;
const SLOT_MATCAP2_MASK: i32 = 17;
const SLOT_RIM: i32 = 18;
const SLOT_OUTLINE: i32 = 19;
const SLOT_OUTLINE_WIDTH: i32 = 20;
const SLOT_MAIN2: i32 = 21;
const SLOT_MAIN2_MASK: i32 = 22;
const SLOT_MAIN3: i32 = 23;
const SLOT_MAIN3_MASK: i32 = 24;
const SLOT_BUMP2: i32 = 25;
const SLOT_BUMP2_MASK: i32 = 26;
const SLOT_RIM_SHADE_MASK: i32 = 27;
const SLOT_BACKLIGHT: i32 = 28;
const SLOT_SMOOTHNESS: i32 = 29;
const SLOT_METALLIC: i32 = 30;
const SLOT_REFL_COLOR: i32 = 31;
const SLOT_GLITTER: i32 = 32;
const SLOT_ANISO_TANGENT: i32 = 33;
const SLOT_ANISO_MASK: i32 = 34;
const SLOT_ANISO_NOISE: i32 = 35;
const SLOT_MATCAP_BUMP: i32 = 36;
const SLOT_MATCAP2_BUMP: i32 = 37;

