//! ドックのパネルの中身。
pub mod assets;
pub mod brush_detail;
pub mod brush_props;
pub mod brushes;
pub mod channels;
pub mod color;
pub mod fill_props;
pub mod layer_props;
pub mod layers;
pub mod material;
pub mod path_props;
pub mod pose;
pub mod properties;
pub mod region_props;
pub mod stencil_props;
pub mod texture_sets;
pub mod tip_library;
pub mod view3d;
