#!/usr/bin/env python3
"""csbindgen が作った P/Invoke の宣言（crates/yolu-bridge/generated/LiveLinkNative.g.cs）を、関数ポインターで呼ぶ形に書き換える。

[DllImport] の宣言は、Unity が一度読んだネイティブのライブラリをエディタが終わるまで手放さないため、パッケージの中のファイルが
Windows では差し替え・削除できなくなる。呼び手が自分でライブラリを（コピーから）読み、関数の番地を渡す形にすると、
ライブラリを読む場所と、更新のときの扱いを C# の側が決められる（Editor/LiveLink/Native/LiveLinkNativeLoader.cs）。

  gen-livelink-native.py 入力.g.cs 出力.g.cs

呼び方（名前・引数・戻り値）は元の宣言と同じ。構造体の宣言はそのまま写す。
"""
import re
import sys

EXTERN = re.compile(
    r'^(?P<indent>\s*)\[DllImport\((?P<attr>[^\n]*)\)\]\n'
    r'\s*internal static extern (?P<ret>[\w*]+) (?P<name>\w+)\((?P<params>[^)]*)\);',
    re.M,
)
ENTRY = re.compile(r'EntryPoint = "(\w+)"')


def split_params(text):
    text = text.strip()
    if not text:
        return []
    out = []
    for part in text.split(','):
        part = part.strip()
        kind, _, name = part.rpartition(' ')
        if not kind or not name:
            raise ValueError(f'引数を読めない: {part!r}')
        out.append((kind.strip(), name.strip()))
    return out


def transform(source):
    entries = []

    def wrap(match):
        name = match['name']
        entry = ENTRY.search(match['attr'])
        if not entry or entry.group(1) != name:
            raise ValueError(f'{name}: EntryPoint が関数名と違う')
        params = split_params(match['params'])
        ret = match['ret']
        types = ', '.join([k for k, _ in params] + [ret])
        decl = ', '.join(f'{k} {n}' for k, n in params)
        args = ', '.join(n for _, n in params)
        entries.append(name)
        indent = match['indent']
        return (
            f'{indent}internal static {ret} {name}({decl}) => '
            f'((delegate* unmanaged[Cdecl]<{types}>)Pointer(p_{name}))({args});\n'
            f'{indent}static IntPtr p_{name};'
        )

    body, count = EXTERN.subn(wrap, source)
    if count == 0 or 'DllImport' in body:
        raise ValueError('宣言を全部は書き換えられなかった')
    body = body.replace('        const string __DllName = "yolu_bridge";\n', '')
    binding = ['', '        /// <summary>ライブラリの関数の番地を結ぶ（<paramref name="symbol"/> は、名前から番地を引く。無い関数があれば EntryPointNotFoundException）。</summary>',
               '        internal static void Bind(Func<string, IntPtr> symbol)', '        {']
    binding += [f'            p_{n} = Resolve(symbol, "{n}");' for n in entries]
    binding += ['        }', '',
                '        static IntPtr Resolve(Func<string, IntPtr> symbol, string name)',
                '        {',
                '            var address = symbol(name);',
                '            if (address == IntPtr.Zero) throw new EntryPointNotFoundException(name);',
                '            return address;',
                '        }', '',
                '        /// <summary>結んでいない関数を呼んで、エディタを落とさない。</summary>',
                '        static IntPtr Pointer(IntPtr address)',
                '        {',
                '            if (address == IntPtr.Zero) throw new InvalidOperationException("The Live Link library is not loaded.");',
                '            return address;',
                '        }']
    # クラスの最後の `}` の前に足す。最初の構造体より前にあるクラスの閉じ括弧を探す
    marker = '    }\n\n'
    head, sep, tail = body.partition('\n    }\n')
    if not sep:
        raise ValueError('クラスの終わりが見つからない')
    body = head + '\n' + '\n'.join(binding) + '\n    }\n' + tail
    return body, entries


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    with open(sys.argv[1], encoding='utf-8') as f:
        source = f.read()
    out, entries = transform(source)
    header = '// <auto-generated>\n// Generated by tools/gen-livelink-native.py from the csbindgen output (function pointers instead of DllImport).\n// DON\'T CHANGE THIS DIRECTLY.\n// </auto-generated>\n'
    out = out.replace('// <auto-generated>\n// This code is generated by csbindgen.\n// DON\'T CHANGE THIS DIRECTLY.\n// </auto-generated>\n', header, 1)
    with open(sys.argv[2], 'w', encoding='utf-8', newline='\n') as f:
        f.write(out)
    print(f'{len(entries)} 個の関数を書き換えた: {sys.argv[2]}')


if __name__ == '__main__':
    main()
